name: expense_tracker1
description: A new Flutter project for tracking expenses

publish_to: 'none' # Remove this line if you plan to publish the app

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"  # Make sure this is compatible with your Flutter version

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.40.0  # Pie chart dependency
  sqflite: ^2.0.0+4  # SQLite for local database storage
  path: ^1.8.0  # Path for working with file system paths in SQLite
  provider: ^6.1.3  # For state management (optional, if you're using provider)
  shared_preferences: ^2.1.0  # For storing user preferences (optional)
  firebase_auth: ^4.6.0  # Firebase Authentication (if using Firebase for login/signup)
  google_fonts: ^4.0.3  # For custom fonts (optional, if you want to style your app)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # For linting Flutter code and following best practices

flutter:
  uses-material-design: true  # Enable Material Design widgets
  assets:
    - assets/images/  # Include any assets (images, fonts, etc.)
